version: '3.1'

services:
  db: 
    image: mariadb
    container_name: cdc-core-dbserver
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cdc-core-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
